# Configuración del puerto
server:
  port: 8087

custom:
  activeprofileName: dev

# Configuración de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Configuración de la base de datos H2
spring:
  datasource:
    url: jdbc:h2:mem:teacher
    username: sa
    password: qwerty
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false

# Configuración de Swagger/OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
  packagesToScan: com.bolivariano.teacher.controller
  pathsToMatch: /teacher/**,/teacher-assign/**

# Configuración de endpoints de administración
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
